const app = document.querySelector('#app');
app.innerHTML = `
  <main class="shell">
    <header><p class="eyebrow">OPTIMA-X</p><h1>Adaptive Logistics Decision Engine</h1><p>Forecast, route, optimize, and explain decisions in a reproducible simulation.</p></header>
    <section class="grid"><article><span>Simulation</span><strong id="orders">—</strong><small>total orders</small></article><article><span>Service level</span><strong id="served">—</strong><small>delivered orders</small></article><article><span>Objective</span><strong id="cost">—</strong><small>baseline cost</small></article></section>
    <button id="run">Run seeded scenario</button><pre id="output">Ready.</pre>
  </main>`;
const style = document.createElement('style'); style.textContent = `body{margin:0;background:#0f172a;color:#e2e8f0;font-family:Inter,system-ui,sans-serif}.shell{max-width:900px;margin:0 auto;padding:64px 24px}.eyebrow{color:#38bdf8;letter-spacing:.18em;font-weight:700}h1{font-size:clamp(2rem,6vw,4.5rem);max-width:780px;margin:0 0 16px}header p{color:#94a3b8;font-size:1.1rem}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:40px 0}.grid article{background:#1e293b;border:1px solid #334155;border-radius:16px;padding:24px}.grid span,.grid small{display:block;color:#94a3b8}.grid strong{display:block;font-size:2rem;margin:10px 0}button{background:#38bdf8;border:0;border-radius:10px;padding:12px 18px;font-weight:700;cursor:pointer}pre{margin-top:24px;background:#020617;border-radius:12px;padding:20px;overflow:auto;color:#7dd3fc}@media(max-width:650px){.grid{grid-template-columns:1fr}}`; document.head.append(style);
document.querySelector('#run').onclick = async () => { const response = await fetch('http://localhost:8000/api/v1/simulation/run', {method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({seed:42,duration_hours:2,zones:3,vehicles:4,orders_per_hour:3})}); const data = await response.json(); const m=data.metrics; document.querySelector('#orders').textContent=m.total_orders; document.querySelector('#served').textContent=m.delivered_orders; document.querySelector('#cost').textContent=m.total_cost; document.querySelector('#output').textContent=JSON.stringify(data,null,2); };
