name: java-dsa
on: [push, pull_request]
jobs:
  junit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - run: mvn -B -f java-dsa/pom.xml test
